### ISSUE TITLE
SCSI INQUIRY command fails on FreeBSD (no mass storage block device created)

### ISSUE THREAD

**Issue by saper** [f-secure-foundry/armory-ums#2] opened 2020-10-24 10:25 UTC
imx_usb has successfully booted armory-ums on my FreeBSD 11.4 laptop, but the mass storage device
does not get created:

```
Oct 24 12:15:53 radziecki kernel: ugen8.4: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8
Oct 24 12:15:53 radziecki kernel: uhid0 on uhub10
Oct 24 12:15:53 radziecki kernel: uhid0: <Freescale Flash> on usbus8
Oct 24 12:18:09 radziecki kernel: uhid0: at uhub10, port 3, addr 4 (disconnected)
Oct 24 12:18:09 radziecki kernel: uhid0: detached
Oct 24 12:18:10 radziecki kernel: ugen8.4: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8 (disconnected)
Oct 24 12:18:14 radziecki kernel: ugen8.4: <TamaGo Storage Media> at usbus8
Oct 24 12:18:14 radziecki kernel: umass0 on uhub10
Oct 24 12:18:14 radziecki kernel: umass0: <TamaGo Storage Media, class 0/0, rev 2.00/0.01, addr 4> on usbus8
Oct 24 12:18:14 radziecki kernel: umass0:  SCSI over Bulk-Only; quirks = 0xc101
Oct 24 12:18:14 radziecki kernel: umass0:5:0: Attached to scbus5
Oct 24 12:18:14 radziecki kernel: (probe0:umass-sim0:0:0:0): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 24 12:18:14 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 24 12:18:14 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 24 12:18:15 radziecki kernel: (probe0:umass-sim0:0:0:0): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 24 12:18:15 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 24 12:18:15 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 24 12:18:16 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 24 12:18:17 radziecki kernel: (probe0:umass-sim0:0:0:0): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 24 12:18:17 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 24 12:18:17 radziecki kernel: (probe0:umass-sim0:0:0:0): Error 5, Retries exhausted
```

My USB-Armory Mk II device descriptor before booting (blank device):

```
> sudo usbconfig -d 8.4 dump_device_desc
ugen8.4: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (10mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0200 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x15a2 
  idProduct = 0x0080 
  bcdDevice = 0x0001 
  iManufacturer = 0x0001  <Freescale SemiConductor Inc >
  iProduct = 0x0002  <SE Blank 6ULL>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001 
```

and after the image gets loaded:

```
> sudo usbconfig -d 8.4 dump_device_desc
ugen8.4: <TamaGo Storage Media> at usbus8, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0200 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x1209 
  idProduct = 0x2702 
  bcdDevice = 0x0001 
  iManufacturer = 0x0001  <TamaGo>
  iProduct = 0x0002  <Storage Media>
  iSerialNumber = 0x0003  <.....>
  bNumConfigurations = 0x0001 
```

USB communications with the device work fine otherwise - for example, the Debian image boots fine and communicates with FreeBSD when using `if_urndis` kernel module.

**Comment by andrejro** [comment] 2020-10-26 13:37
Confirming we can reproduce the error. The TamaGo USB storage driver was tested under Linux, Windows and Mac OS X, we never tested it on BSDs. Thanks for rising this issue, we will investigate further.

**Comment by abarisani** [comment] 2020-10-26 16:29
@saper do you happen to have a USB armory Mk II debug accessory by chance ? The serial console from the armory would help identifying the SCSI command which is sent, but not currently supported as it hasn't been probably seen on Linux/Windows/macOS.

If not don't worry and we'll try to setup our own install to figure it out, but in case you have it, it would help.

**Comment by saper** [comment] 2020-10-27 21:23
@abarisani It's on the way :) I realized after buying Mk II that I have no serial console connection so I had to order the accessory later. I hope that it arrives within 1 or 2 days.

**Comment by saper** [comment] 2020-10-27 21:42
In the meantime I have produced a [dump file of USB commands on the FreeBSD side](https://ylog.eu/tmp/scsi.dump) after the image boots (produced with `imx_usb dist/armory-ums.imx && usbdump -i usbus8 -s 0 -f 2 -w scsi.dump`).

You can read an ASCII dump of it using `usbdump -r scsi.dump -v`.

**Comment by saper** [comment] 2020-10-28 11:51
So I got the debug accessory today and unlike the Debian image booting - nothing get displayed to the serial console when booting with imx_usb - could this be https://github.com/f-secure-foundry/tamago-example/issues/4 ?

**Comment by abarisani** [comment] 2020-10-28 12:15
That has been fixed, I just updated the issue with the solution. Anyway we can now debug in qemu so we are working on it there, thanks!

**Comment by abarisani** [comment] 2020-10-29 10:00
As of https://github.com/f-secure-foundry/armory-ums/commit/be39a06c9fa318a587c9715b6c4a67eeb30de152 this should be now fixed.

Could you please test the latest HEAD? If you confirm a working fix I will make a new binary release then. Thanks!

**Comment by saper** [comment] 2020-10-30 21:02
Great! I think I neeed to fix my tamago first (some tests failed there)

```
gmake TAMAGO=/home/saper/sw/tamago-go/bin/go
GO_EXTLINK_ENABLED=0 CGO_ENABLED=0 GOOS=tamago GOARM=7 GOARCH=arm /home/saper/sw/tamago-go/bin/go build -tags linkramsize -ldflags "-s -w -T 0x80010000  -E _rt0_arm_tamago -R 0x1000 -X 'main.Build=saper@radziecki on 2020-10-30 21:01:38' -X 'main.Revision=b4eb71b'" -o armory-ums
# github.com/f-secure-foundry/armory-ums
runtime.chansend: relocation target runtime.nanotime not defined
runtime.send: relocation target runtime.nanotime not defined
(...)
```

**Comment by saper** [comment] 2020-10-31 11:47
So I have cross-built everything on Linux and I seem to get the eMMC as `da0`:

```
Oct 31 12:45:14 radziecki kernel: ugen8.6: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8
Oct 31 12:45:14 radziecki kernel: uhid0 on uhub10
Oct 31 12:45:14 radziecki kernel: uhid0: <Freescale Flash> on usbus8
Oct 31 12:45:35 radziecki kernel: uhid0: at uhub10, port 3, addr 6 (disconnected)
Oct 31 12:45:35 radziecki kernel: uhid0: detached
Oct 31 12:45:36 radziecki kernel: ugen8.6: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8 (disconnected)
Oct 31 12:45:38 radziecki kernel: ugen8.6: <TamaGo Storage Media> at usbus8
Oct 31 12:45:38 radziecki kernel: umass0 on uhub10
Oct 31 12:45:38 radziecki kernel: umass0: <TamaGo Storage Media, class 0/0, rev 2.00/0.01, addr 6> on usbus8
Oct 31 12:45:38 radziecki kernel: umass0:  SCSI over Bulk-Only; quirks = 0x4100
Oct 31 12:45:38 radziecki kernel: umass0:5:0: Attached to scbus5
Oct 31 12:45:38 radziecki kernel: da0 at umass-sim0 bus 0 scbus5 target 0 lun 0
Oct 31 12:45:38 radziecki kernel: da0: <F-Secure USB armory Mk II 1.00> Removable Direct Access SPC-3 SCSI device
Oct 31 12:45:38 radziecki kernel: da0: Serial Number 85C7E063D2793F33
Oct 31 12:45:38 radziecki kernel: da0: 40.000MB/s transfers
Oct 31 12:45:38 radziecki kernel: da0: 14952MB (30621696 512 byte sectors)
Oct 31 12:45:38 radziecki kernel: da0: quirks=0x2<NO_6_BYTE>
```

**Comment by saper** [comment] 2020-10-31 11:50
However, when doing the SD-Card trick it does not work:

```
Oct 31 12:48:54 radziecki kernel: ugen8.6: <Freescale SemiConductor Inc SE Blank 6ULL> at usbus8 (disconnected)
Oct 31 12:48:56 radziecki kernel: ugen8.6: <TamaGo Storage Media> at usbus8
Oct 31 12:48:57 radziecki kernel: umass0 on uhub10
Oct 31 12:48:57 radziecki kernel: umass0: <TamaGo Storage Media, class 0/0, rev 2.00/0.01, addr 6> on usbus8
Oct 31 12:48:57 radziecki kernel: umass0:  SCSI over Bulk-Only; quirks = 0x4000
Oct 31 12:48:57 radziecki kernel: umass0:5:0: Attached to scbus5
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:57 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 31 12:48:58 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:58 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:58 radziecki kernel: (probe0:umass-sim0:0:0:0): Retrying command
Oct 31 12:48:59 radziecki kernel: (probe0:umass-sim0:0:0:0): REPORT LUNS. CDB: a0 00 00 00 00 00 00 00 00 10 00 00 
Oct 31 12:48:59 radziecki kernel: (probe0:umass-sim0:0:0:0): CAM status: CCB request completed with an error
Oct 31 12:48:59 radziecki kernel: (probe0:umass-sim0:0:0:0): Error 5, Retries exhausted
Oct 31 12:49:03 radziecki kernel: (probe0:umass-sim0:0:0:1): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 31 12:49:03 radziecki kernel: (probe0:umass-sim0:0:0:1): CAM status: CCB request completed with an error
Oct 31 12:49:03 radziecki kernel: (probe0:umass-sim0:0:0:1): Retrying command
Oct 31 12:49:04 radziecki kernel: (probe0:umass-sim0:0:0:1): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 31 12:49:04 radziecki kernel: (probe0:umass-sim0:0:0:1): CAM status: CCB request completed with an error
Oct 31 12:49:04 radziecki kernel: (probe0:umass-sim0:0:0:1): Retrying command
Oct 31 12:49:05 radziecki kernel: (probe0:umass-sim0:0:0:1): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 31 12:49:05 radziecki kernel: (probe0:umass-sim0:0:0:1): CAM status: CCB request completed with an error
Oct 31 12:49:05 radziecki kernel: (probe0:umass-sim0:0:0:1): Retrying command
Oct 31 12:49:06 radziecki kernel: (probe0:umass-sim0:0:0:1): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 31 12:49:06 radziecki kernel: (probe0:umass-sim0:0:0:1): CAM status: CCB request completed with an error
Oct 31 12:49:06 radziecki kernel: (probe0:umass-sim0:0:0:1): Retrying command
Oct 31 12:49:07 radziecki kernel: (probe0:umass-sim0:0:0:1): INQUIRY. CDB: 12 00 00 00 24 00 
Oct 31 12:49:07 radziecki kernel: (probe0:umass-sim0:0:0:1): CAM status: CCB request completed with an error
Oct 31 12:49:07 radziecki kernel: (probe0:umass-sim0:0:0:1): Error 5, Retries exhausted
Oct 31 12:49:09 radziecki kernel: (da0:umass-sim0:0:0:0): got CAM status 0x44
Oct 31 12:49:09 radziecki kernel: (da0:umass-sim0:0:0:0): fatal error, failed to attach to device
Oct 31 12:49:09 radziecki kernel: g_access(952): provider da0 has error 6 set
```

The original image reported only `12 00 00 00 24 00` error as in the OP, so the `a0 00 00 00 00 00 00 00 00 10 00 00` are new with b4eb71bc41abf9ba84054f2bd93b4f34ca8a1a84

**Comment by abarisani** [comment] 2020-10-31 17:55
> Great! I think I neeed to fix my tamago first (some tests failed there)
> 
> ```
> gmake TAMAGO=/home/saper/sw/tamago-go/bin/go
> GO_EXTLINK_ENABLED=0 CGO_ENABLED=0 GOOS=tamago GOARM=7 GOARCH=arm /home/saper/sw/tamago-go/bin/go build -tags linkramsize -ldflags "-s -w -T 0x80010000  -E _rt0_arm_tamago -R 0x1000 -X 'main.Build=saper@radziecki on 2020-10-30 21:01:38' -X 'main.Revision=b4eb71b'" -o armory-ums
> # github.com/f-secure-foundry/armory-ums
> runtime.chansend: relocation target runtime.nanotime not defined
> runtime.send: relocation target runtime.nanotime not defined
> (...)
> ```

I think this needs a separate issue to be tracked, not sure why it behaves differently on non-Linux.

**Comment by abarisani** [comment] 2020-10-31 18:05
Could you try this patch for me? Thanks.

```
diff --git a/scsi.go b/scsi.go
index 6d3c7c0..e80faa4 100644
--- a/scsi.go
+++ b/scsi.go
@@ -128,7 +128,7 @@ func modeSense(length int) (data []byte, err error) {
 }
 
 // p179, 3.33 REPORT LUNS command, SCSI Commands Reference Manual, Rev. J
-func reportLUNs() (data []byte, err error) {
+func reportLUNs(length int) (data []byte, err error) {
        buf := new(bytes.Buffer)
        luns := len(cards)
 
@@ -139,7 +139,13 @@ func reportLUNs() (data []byte, err error) {
                binary.Write(buf, binary.BigEndian, uint64(lun))
        }
 
-       return buf.Bytes(), nil
+       data = buf.Bytes()
+
+       if length < buf.Len() {
+               data = data[0:length]
+       }
+
+       return
 }
 
 // p155, 3.22 READ CAPACITY (10) command, SCSI Commands Reference Manual, Rev. J
@@ -235,7 +241,7 @@ func handleCDB(cmd [16]byte, cbw *usb.CBW) (csw *usb.CSW, data []byte, err error
        case MODE_SENSE_6, MODE_SENSE_10:
                data, err = modeSense(length)
        case REPORT_LUNS:
-               data, err = reportLUNs()
+               data, err = reportLUNs(length)
        case READ_FORMAT_CAPACITIES:
                data, err = readFormatCapacities(card)
        case READ_CAPACITY_10:
```

**Comment by saper** [comment] 2020-10-31 20:07
Thank you, this works. da0 reports back with the SD-Card.

**Comment by abarisani** [comment] 2020-10-31 20:29
The fix is in https://github.com/f-secure-foundry/armory-ums/commit/dbf2227c30968058c9955217f3fe9eee3ef8899a

I added a similar fix to `READ CAPACITY (16)` which should not affect anything, just improve in case a different length is requested. May I ask you to test HEAD again to ensure that both fixes are fine? If you confirm I will close the ticket and make a new binary release. Thanks!

**Comment by saper** [comment] 2020-10-31 22:38
With dbf2227 I am getting one device only.

Maybe this is because we report two LUNs but both are 0?

```
# camcontrol reportluns 5:0
2 LUNs found
0
0
```

From what I see in the [kernel code](https://github.com/freebsd/freebsd/blob/releng/11.4/sys/cam/scsi/scsi_xpt.c#L1321-L1332) FreeBSD starts with conservative 16 byte buffer and retries the command if a larger buffer is needed. (I am not sure if it is done even if no ILLEGAL REQUEST is returned per SCSI reference 2.2.6)

**Comment by saper** [comment] 2020-10-31 22:45
Read capacity returns this:

    # camcontrol readcap 5:0:0
    Last Block: 62333951, Block Length: 512 bytes

Also tried INQUIRY (-D "return standard inquiry data"), nothing returned (but I also get nothing from my disks).

    # camcontrol inquiry 5:0 -D
    # camcontrol inquiry 5:0 -S
    85C7E063D2793F33
    # camcontrol inquiry 5:0 -R
    pass3: 40.000MB/s transfers

So serial number and transfers are fine.

**Comment by saper** [comment] 2020-11-01 11:15
Unfortunately, probably due too many insertions/removals the USB-C connector of my Armory broke off today, so I can only access it via the debug accessory UART....

**Comment by abarisani** [comment] 2020-11-01 13:15
I am sorry to hear that, this is unusual (I made dozen connections a day). Please email us directly for a free replacement.

In the meantime, for my understanding, the patch in https://github.com/f-secure-foundry/armory-ums/issues/2#issuecomment-719967763 was working and it's only the `READ CAPACITY (16)` change (added in my commit) which broke things, correct?

**Comment by saper** [comment] 2020-11-01 17:06
Thank you! I haven't tried READ CAPACITY before but the above means it was working ok after your patch.

What I think is broken is this: having both SD-Card and (unformatted) eMMC I'd expect to have two devices, but I get only one (FreeBSD says there are two luns but both have number "0" which is probably because the answer got re-used twice). 

What I'd try next is to report an error if the buffer is too small.

**Comment by abarisani** [comment] 2020-11-02 08:55
Commit https://github.com/f-secure-foundry/armory-ums/commit/66b36b49c13024d7e26cc263e391c78d78fef3e6 should adjust the length of `READ CAPACITY (16)` correctly.

As far as `REPORT LUNS` goes that was fixed [here](https://github.com/f-secure-foundry/armory-ums/commit/be39a06c9fa318a587c9715b6c4a67eeb30de152#diff-65a128859619695ffa1b749f348ffe48352af4948b5db61893b38b198eb9ed96R130) and [here](https://github.com/f-secure-foundry/armory-ums/commit/dbf2227c30968058c9955217f3fe9eee3ef8899a#diff-65a128859619695ffa1b749f348ffe48352af4948b5db61893b38b198eb9ed96R131) in a manner that supports both SD and MMC exposed. The different LUN numbers are set [here](https://github.com/f-secure-foundry/armory-ums/blob/master/scsi.go#L139) so both should not be ever 0.

Please contact us at the email addressed specified [here](https://github.com/f-secure-foundry/usbarmory/wiki#support) to get your free replacement going. Thanks!

**Comment by andrejro** [comment] 2020-11-02 09:46
> Great! I think I neeed to fix my tamago first (some tests failed there)
> 
> ```
> gmake TAMAGO=/home/saper/sw/tamago-go/bin/go
> GO_EXTLINK_ENABLED=0 CGO_ENABLED=0 GOOS=tamago GOARM=7 GOARCH=arm /home/saper/sw/tamago-go/bin/go build -tags linkramsize -ldflags "-s -w -T 0x80010000  -E _rt0_arm_tamago -R 0x1000 -X 'main.Build=saper@radziecki on 2020-10-30 21:01:38' -X 'main.Revision=b4eb71b'" -o armory-ums
> # github.com/f-secure-foundry/armory-ums
> runtime.chansend: relocation target runtime.nanotime not defined
> runtime.send: relocation target runtime.nanotime not defined
> (...)
> ```

When compiling tamago-go please checkout "latest" tag.

**Comment by abarisani** [comment] 2020-11-02 11:28
It turns out that the `REPORT LUNS` response format was incorrect, after some digging this should now be correct: https://github.com/f-secure-foundry/armory-ums/commit/39e2ed4306c66341feefe39ed925be7c10506a6c

We made a [new binary release](https://github.com/f-secure-foundry/armory-ums/releases/tag/v20201102) reflecting these changes.

In case there are further issues on FreeBSD kindly re-open the issue.

Thanks!

**Closed as completed** 2020-11-02 11:39 UTC

**Comment by saper** [comment] 2020-11-04 14:56
Big thanks for the device! So it works perfectly now:

```
mass0: <TamaGo Storage Media, class 0/0, rev 2.00/0.01, addr 7> on usbus8
umass0:  SCSI over Bulk-Only; quirks = 0x4000
umass0:5:0: Attached to scbus5
da0 at umass-sim0 bus 0 scbus5 target 0 lun 0
da0: <F-Secure USB armory Mk II 1.00> Removable Direct Access SPC-3 SCSI device
da0: Serial Number ZZZZZZZZZZZZZZZZ
da0: 40.000MB/s transfers
da0: 30436MB (62333952 512 byte sectors)
da0: quirks=0x2<NO_6_BYTE>
da1 at umass-sim0 bus 0 scbus5 target 0 lun 1
da1: <F-Secure USB armory Mk II 1.00> Removable Direct Access SPC-3 SCSI device
da1: Serial Number ZZZZZZZZZZZZZZZZ
da1: 40.000MB/s transfers
da1: 14952MB (30621696 512 byte sectors)
da1: quirks=0x2<NO_6_BYTE>

# camcontrol reportluns 5:0
2 LUNs found
0
1
# camcontrol readcap 5:0:1
Last Block: 30621695, Block Length: 512 bytes
# camcontrol readcap 5:0:0
Last Block: 62333951, Block Length: 512 bytes
```

And the Linux partitions on the SD card get recognized as well.

```
# fuse-ext2 /dev/da0s1 /mnt
Mounting /dev/da0s1 Read-Only.
Use 'force' or 'rw+' options to enable Read-Write mode
# grep usbarmory /mnt/etc/passwd
usbarmory:x:1000:1000::/home/usbarmory:/bin/bash
```
